src/objects/Sprint__c.object
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subtask__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>PlanTime__c</fullName>
        <label>PlanTime</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SpendTime__c</fullName>
        <label>SpendTime</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Subtasks</relationshipLabel>
        <relationshipName>Subtasks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtask</label>
    <nameField>
        <label>Subtask Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subtasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>backlog</fullName>
                </value>
                <value>
                    <fullName>sprint</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Spend_Time__c</fullName>
        <label>Total Spend Time</label>
        <summarizedField>Subtask__c.SpendTime__c</summarizedField>
        <summaryForeignKey>Subtask__c.Task__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Subtask_Estimate__c</fullName>
        <label>Total Subtask Estimate</label>
        <summarizedField>Subtask__c.PlanTime__c</summarizedField>
        <summaryForeignKey>Subtask__c.Task__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScrumBacklogService.cls
/**
 * Created by YuriiDyvak on 26.07.2019.
 */

public class ScrumBacklogService {

    public List<ScrumTaskRecord> getBacklogs() {

        List<ScrumTaskRecord> result = new List<ScrumTaskRecord>();

        UniversalSelector selector = (UniversalSelector) Application.Selector.get(Task__c.getSObjectType());
        List<Task__c> backlogs = (List<Task__c>) selector.queryBuilder()
                .querySelect()
                .queryFields('Id, Name, Assignee__c, Description__c, Total_Subtask_Estimate__c, Total_Spend_Time__c, Sprint__c')
                .queryFrom(Task__c.getSObjectType())
                .queryWhere('Stage__c', 'backlog')
                .execute();

        System.debug('Backlogs ' + backlogs);


        List<Subtask__c> subtasks = getSubtasksForTasks(backlogs);

        System.debug(subtasks);

        for (Task__c backlog : backlogs) {
            if (!subtasks.isEmpty()) {
                for (Subtask__c subtask : subtasks) {
                    if (subtask.Task__c == backlog.Id) {
                        result.add(new ScrumTaskRecord(backlog, subtasks));
                    } else {
                        result.add(new ScrumTaskRecord(backlog));
                    }
                }
            } else {
                result.add(new ScrumTaskRecord(backlog));
            }
        }

        System.debug(result);
        return result;
    }

    public List<Subtask__c> getSubtasksForTasks(List<Task__c> tasks) {
        Set<Id> taskIds = new Set<Id>();
        for (Task__c task : tasks) {
            taskIds.add(task.Id);
        }

        UniversalSelector selector = (UniversalSelector) Application.Selector.get(Subtask__c.getSobjectType()) ;
        return (List<Subtask__c>) selector
                .queryBuilder()
                .querySelect()
                .queryFields('Id, Name, Task__c, SpendTime__c, PlanTime__c')
                .queryFrom(Subtask__c.getSObjectType())
                .queryWhere('Task__c', taskIds)
                .execute();
    }

    public void deleteById(String backlogId) {
        UniversalSelector selector = (UniversalSelector) Application.Selector.get(Task__c.getSObjectType());
        selector.deleteById(backlogId);
    }

    public void moveTaskToSprint(String sprintId, String taskId) {
        UniversalSelector selector = (UniversalSelector) Application.Selector.get(Task__c.getSObjectType());
        Task__c task = (Task__c) selector.findById(taskId);
        task.Sprint__c = sprintId;
        task.Stage__c = 'sprint';
        selector.save(task);
    }

    public void moveTaskToBacklog(String taskId) {
        UniversalSelector selector = (UniversalSelector) Application.Selector.get(Task__c.getSObjectType());
        Task__c task = (Task__c) selector.findById(taskId);
        task.Stage__c = 'backlog';
        selector.save(task);
    }
}