src/objects/Sprint__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>new</fullName>
                </value>
                <value>
                    <fullName>in progress</fullName>
                </value>
                <value>
                    <fullName>completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subtask__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Subtasks</relationshipLabel>
        <relationshipName>Subtasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SpendTime__c</fullName>
        <label>SpendTime</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Subtasks</relationshipLabel>
        <relationshipName>Subtasks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>new</fullName>
                </value>
                <value>
                    <fullName>in progress</fullName>
                </value>
                <value>
                    <fullName>completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subtask</label>
    <nameField>
        <label>Subtask Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subtasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Planning_time__c</fullName>
        <label>Planning time</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>backlog</fullName>
                </value>
                <value>
                    <fullName>sprint</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>new</fullName>
                </value>
                <value>
                    <fullName>in progress</fullName>
                </value>
                <value>
                    <fullName>completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScrumSprintServiceTest.cls
/**
 * Created by YuriiDyvak on 07.08.2019.
 */

@isTest
public with sharing class ScrumSprintServiceTest {

    @TestSetup
    public static void setUp() {

        Project__c project = new Project__c(Name = 'new project');
        insert project;

        Sprint__c sprint = new Sprint__c(Name = 'newSprint', Project__c = project.Id);
        insert sprint;

        List<Task__c> tasks = new List<Task__c>();
        for (Integer i = 0; i < 10; i++) {
            tasks.add(new Task__c(Name = 'newTask ' + 1, Sprint__c = sprint.Id, Project__c = project.Id, Planning_time__c = 5, Type__c = 'new', Stage__c = 'sprint'));
        }
        insert tasks;

        List<Subtask__c> subtasks = new List<Subtask__c>();
        Task__c task = [Select Id From Task__c Limit 1];
        for (Integer i = 0; i < 10; i++) {
            subtasks.add(new Subtask__c(Name = 'new subtask', Project__c = project.Id, Type__c = 'new', Task__c = task.Id, SpendTime__c = 5));
        }
        insert subtasks;

    }


    @isTest
    public static void getSprints() {

        Project__c project = [SELECT Id FROM Project__c WHERE Name = 'new project'];
        System.debug(project);

        ScrumSprintService service = (ScrumSprintService) Application.Service.get(ScrumSprintService.class);
        List<ScrumSprintRecord> result = service.getSprintRecordsForProject(project.Id);
        System.debug(result);
    }

}