src/objects/Sprint__c.object
<CustomObject>
    <fields>
        <fullName>Date_finish__c</fullName>
        <formula>TODAY() + 7</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date finish</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Day__c</fullName>
        <label>Start Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Estimate__c</fullName>
        <label>Total Estimate</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 week</fullName>
                </value>
                <value>
                    <fullName>2 weeks</fullName>
                </value>
                <value>
                    <fullName>1 month</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Estimate_of_Tasks__c</fullName>
        <label>Total Estimate of Tasks</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>new</fullName>
                </value>
                <value>
                    <fullName>in progress</fullName>
                </value>
                <value>
                    <fullName>completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subtask__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>PlanTime__c</fullName>
        <label>PlanTime</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Subtasks</relationshipLabel>
        <relationshipName>Subtasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SpendTime__c</fullName>
        <label>SpendTime</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Subtasks</relationshipLabel>
        <relationshipName>Subtasks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>new</fullName>
                </value>
                <value>
                    <fullName>in progress</fullName>
                </value>
                <value>
                    <fullName>completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subtask</label>
    <nameField>
        <label>Subtask Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subtasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>backlog</fullName>
                </value>
                <value>
                    <fullName>sprint</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Day__c</fullName>
        <label>Start Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Spend_Time__c</fullName>
        <label>Total Spend Time</label>
        <summarizedField>Subtask__c.SpendTime__c</summarizedField>
        <summaryForeignKey>Subtask__c.Task__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Subtask_Estimate__c</fullName>
        <label>Total Subtask Estimate</label>
        <summarizedField>Subtask__c.PlanTime__c</summarizedField>
        <summaryForeignKey>Subtask__c.Task__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>new</fullName>
                </value>
                <value>
                    <fullName>in progress</fullName>
                </value>
                <value>
                    <fullName>completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScrumSprintService.cls
/**
 * Created by YuriiDyvak on 26.07.2019.
 */

public class ScrumSprintService {

    public void removeTaskFromSprint(String recordId) {
        UniversalSelector selector = (UniversalSelector) Application.Selector.get(Task__c.getSobjectType()) ;
        Task__c task = (Task__c) selector.queryBuilder()
                .querySelect()
                .queryFields('Id, Sprint__c')
                .queryFrom(Task__c.getSObjectType())
                .queryWhere('Id', recordId)
                .execute();

        task.Sprint__c = null;
        task.Type__c = 'backlog';
        selector.save((SObject) task);
    }

    public ScrumSprintRecord getSprintRecord(String sprintId) {
        Sprint__c sprint = getSprintById(sprintId);
        List<Task__c> tasks = new List<Task__c>();
        for (Task__c task : sprint.Tasks__r) {
            tasks.add(task);
        }
        List<Subtask__c> subtasks = getSubtasksForTasks(tasks);
        return getSprintRecord(sprint, subtasks);
    }

    public List<ScrumSprintRecord> getSprintRecordsForProject(String id) {
        List<ScrumSprintRecord> result = new List<ScrumSprintRecord>();

        List<Sprint__c> sprints = getTasksForSprintsForProject(id);
        System.debug(sprints);

        List<Task__c> tasks = new List<Task__c>();
        for (Sprint__c sprint : sprints) {
            for (Task__c task : sprint.Tasks__r) {
                tasks.add(task);
            }
        }

        List<Subtask__c> subtasks = getSubtasksForTasks(tasks);

        for (Sprint__c sprint : sprints) {
            result.add(getSprintRecord(sprint, subtasks));
        }
        return result;
    }

    public List<Subtask__c> getSubtasksForTasks(List<Task__c> tasks) {
        Set<Id> taskIds = new Set<Id>();
        for (Task__c task : tasks) {
            taskIds.add(task.Id);
        }

        UniversalSelector selector = (UniversalSelector) Application.Selector.get(Subtask__c.getSobjectType()) ;
        return (List<Subtask__c>) selector
                .queryBuilder()
                .querySelect()
                .queryFields('Id, Name, Task__c, SpendTime__c, PlanTime__c')
                .queryFrom(Subtask__c.getSObjectType())
                .queryWhere('Task__c', taskIds)
                .execute();
    }

    public ScrumSprintRecord getSprintRecord(Sprint__c sprint, List<Subtask__c> subtasks) {
        List<ScrumTaskRecord> taskRecords = new List<ScrumTaskRecord>();
        for (Task__c task : sprint.Tasks__r) {
            List<Subtask__c> taskSubtasks = new List<Subtask__c>();
            for (Subtask__c subtask : subtasks) {
                if (task.Id == subtask.Task__c) {
                    taskSubtasks.add(subtask);
                }
            }
            taskRecords.add(new ScrumTaskRecord(task, taskSubtasks));
        }
        return new ScrumSprintRecord(sprint, taskRecords);
    }

    public List<Sprint__c> getSprintsForProject(String id) {
        UniversalSelector selector = (UniversalSelector) Application.Selector.get(Sprint__c.getSobjectType()) ;
        return (List<Sprint__c>) selector.queryBuilder()
                .querySelect()
                .queryFields('Id, Name, Date_finish__c, Project__c, Start_Day__c, Total_Estimate__c, Type__c')
                .queryFrom(Sprint__c.getSObjectType())
                .queryWhere('Project__c', id)
                .execute();
    }

    public List<Sprint__c> getTasksForSprints(Set<Id> ids) {

        String FIELDS = 'Id, ' +
                'Name, ' +
                'Date_finish__c, ' +
                'Project__c, ' +
                'Start_Day__c, ' +
                'Total_Estimate__c, ' +
                'Type__c, ' +
                '(SELECT Id,Name FROM Task__c';

        UniversalSelector selector = (UniversalSelector) Application.Selector.get(Sprint__c.getSObjectType());

        return (List<Sprint__c>) selector.queryBuilder()
                .querySelect()
                .queryFields(FIELDS)
                .queryFrom(Task.getSobjectType())
                .queryWhere('Sprint__c', ids)
                .execute();

    }

    public List<Sprint__c> getTasksForSprintsForProject(String id) {

        String FIELDS = 'Id, ' +
                'Name, ' +
                'Date_finish__c, ' +
                'Project__c, ' +
                'Start_Day__c, ' +
                'Total_Estimate__c, ' +
                'Total_Track_Time__c, ' +
                'Total_Estimate_of_Tasks__c, ' +
                'Type__c, ' +
                '(SELECT Id, ' +
                'Name, ' +
                'Description__c, ' +
                'Total_Subtask_Estimate__c, ' +
                'Total_Spend_Time__c FROM Tasks__r WHERE Stage__c = \'sprint\')';

        UniversalSelector selector = (UniversalSelector) Application.Selector.get(Sprint__c.getSObjectType());

        return (List<Sprint__c>) selector.queryBuilder()
                .querySelect()
                .queryFields(FIELDS)
                .queryFrom(Sprint__c.getSobjectType())
                .queryWhere('Project__c', id)
                .execute();

    }

    public Sprint__c getSprintById(String sprintId) {

        String FIELDS = 'Id, ' +
                'Name, ' +
                'Date_finish__c, ' +
                'Project__c, ' +
                'Start_Day__c, ' +
                'Total_Estimate__c, ' +
                'Total_Track_Time__c, ' +
                'Total_Estimate_of_Tasks__c, ' +
                'Type__c, ' +
                '(SELECT Id, Name, Description__c, Total_Subtask_Estimate__c, Total_Spend_Time__c FROM Tasks__r WHERE Stage__c = \'sprint\')';

        UniversalSelector selector = (UniversalSelector) Application.Selector.get(Sprint__c.getSObjectType());

        return (Sprint__c) selector.queryBuilder()
                .querySelect()
                .queryFields(FIELDS)
                .queryFrom(Sprint__c.getSobjectType())
                .queryWhere('Id', sprintId)
                .queryLimit(1)
                .execute();
    }

    public void updateSpendTime(List<TrackTime__c> newTrackTimes) {
        List<Sprint__c> result = new List<Sprint__c>();

        Set<Id> sprintIds = new Set<Id>();
        for (SObject trackTime : newTrackTimes) {
            TrackTime__c track = (TrackTime__c) trackTime;
            sprintIds.add(track.Sprint__c);
        }

        List<Sprint__c> sprints = [SELECT Id FROM Sprint__c WHERE Id = :sprintIds];

        List<TrackTime__c> trackTimes = [SELECT Id, Subtask__c, Track__c FROM TrackTime__c WHERE Subtask__c = :sprintIds];

        for (Sprint__c sprint : sprints) {
            Decimal spendTime = 0;

            for (TrackTime__c trackTime : trackTimes) {
                if (trackTime.Sprint__c == sprint.Id) {
                    spendTime += trackTime.Track__c;
                }
            }

            sprint.Total_Track_Time__c = spendTime;
            result.add(sprint);
        }

        update result;

    }

    public void recalculateTotalEstimateOfTasks(List<Sprint__c> sprints) {
        List<Sprint__c> result = new List<Sprint__c>();

        Set<Id> sprintIds = new Set<Id>();
        for (SObject sprint : sprints) {
            sprintIds.add(sprint.Id);
        }

        List<Task__c> tasks = [SELECT Id, Total_Subtask_Estimate__c, Total_Spend_Time__c, Sprint__c FROM Task__c WHERE Sprint__c = :sprintIds];


        for (Sprint__c sprint : sprints) {
            Decimal planningTime = 0;
            Decimal trackedTime = 0;

            for (Task__c task : tasks) {
                if (task.Sprint__c == sprint.Id) {
                    planningTime += task.Total_Subtask_Estimate__c;
                    trackedTime += task.Total_Spend_Time__c;
                }
            }
            System.debug(planningTime + '  ' + trackedTime);

            //sprint.Total_Estimate_of_Tasks__c = planningTime;
            result.add(new Sprint__c(Id = sprint.Id, Total_Estimate_of_Tasks__c = planningTime, Total_Track_Time__c = trackedTime));
        }

        TriggerHandlerExecutor.bypassHandler(SprintHandler.UpdateSprintHandler.class);
        update result;
        TriggerHandlerExecutor.clearBypass(SprintHandler.UpdateSprintHandler.class);
    }

    public void isNotPossibleHaveTwoActiveSprints(List<Sprint__c> sprints) {

        List<Sprint__c> recordsForUpdating = new List<Sprint__c>();

        List<Sprint__c> inProgressSprint = new List<Sprint__c>();

        for (Sprint__c sprint : sprints) {
            if (sprint.Type__c == 'in progress') {
                inProgressSprint.add(sprint);
            }
        }
        if (!inProgressSprint.isEmpty()) {
            Datetime attachCreatedDate = null;
            Id attachId = null;
            for (Sprint__c sprint : inProgressSprint) {

                if (attachCreatedDate == null || sprint.CreatedDate > attachCreatedDate) {
                    attachCreatedDate = sprint.CreatedDate;
                    attachId = sprint.Id;
                }
            }
            recordsForUpdating.clear();
            recordsForUpdating.add(new Sprint__c(Id = attachId, Type__c = 'in progress'));

            clearInProgressSprints();
            System.debug(recordsForUpdating);

            // update records
            TriggerHandlerExecutor.bypassHandler(SprintHandler.UpdateSprintHandler.class);
            update recordsForUpdating;
            TriggerHandlerExecutor.clearBypass(SprintHandler.UpdateSprintHandler.class);
        }
    }

    @TestVisible
    private void clearInProgressSprints() {
        List<Sprint__c> items = [SELECT Id FROM Sprint__c WHERE Type__c = 'in progress'];
        for (Sprint__c item : items) {
            item.Type__c = 'new';
        }

        System.debug(items);

        TriggerHandlerExecutor.bypassHandler(SprintHandler.UpdateSprintHandler.class);
        update items;
        TriggerHandlerExecutor.clearBypass(SprintHandler.UpdateSprintHandler.class);
    }


}