src/objects/Sprint__c.object
<CustomObject>
    <fields>
        <fullName>Date_finish__c</fullName>
        <formula>TODAY() + 7</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date finish</label>
        <type>Date</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>backlog</fullName>
                </value>
                <value>
                    <fullName>sprint</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Spend_Time__c</fullName>
        <label>Total Spend Time</label>
        <summarizedField>Subtask__c.SpendTime__c</summarizedField>
        <summaryForeignKey>Subtask__c.Task__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Subtask_Estimate__c</fullName>
        <label>Total Subtask Estimate</label>
        <summarizedField>Subtask__c.PlanTime__c</summarizedField>
        <summaryForeignKey>Subtask__c.Task__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SchedulerCheckIfSprintDateEndBatch.cls
/**
 * Created by YuriiDyvak on 20.08.2019.
 */


public with sharing class SchedulerCheckIfSprintDateEndBatch implements Database.Batchable<sObject>, Database.Stateful {

    public final String myQuery = '[SELECT Id FROM Sprint__c WHERE Date_finish__c < today]';
    public String errMsg = '';

    public void execute(Database.BatchableContext param1, List<sObject> scope) {
        List<Task__c> recordsForUpdate = new List<Task__c>();

        List<Sprint__c> sprints = (List<Sprint__c>) scope;
        Set<Id> ids = new Set<Id>();
        for (Sprint__c sprint : sprints) {
            ids.add(sprint.Id);
        }
        List<Task__c> tasks = [SELECT Id FROM Task__c WHERE Sprint__c = :ids];
        for (Task__c task : tasks) {
            if (task.Total_Subtask_Estimate__c > task.Total_Spend_Time__c) {
                recordsForUpdate.add(new Task__c(Id = task.Id, Stage__c = 'backlog'));
            }
        }

        update recordsForUpdate;
    }

    public void finish(Database.BatchableContext param1) {
        if (errMsg == '') {
            System.debug('Batch [AccountBatch] has finished : All Account updates are successful!');
        } else {
            System.debug('Batch [AccountBatch] has finished : There were errors. Here are a list of all errors. <br />' + errMsg);
        }
    }

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(myQuery);
    }

}