src/objects/Sprint__c.object
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subtask__c.object
<CustomObject>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Subtasks</relationshipLabel>
        <relationshipName>Subtasks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtask</label>
    <nameField>
        <label>Subtask Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subtasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScrumTrackTimeService.cls
/**
 * Created by YuriiDyvak on 13.08.2019.
 */

public with sharing class ScrumTrackTimeService {

    public void trackTime(String subtaskId, String sprintId, String taskId, Integer trackTime) {
        AbstractSelector selector = (AbstractSelector) Application.Selector.get(TrackTime__c.getSObjectType());
        TrackTime__c track = new TrackTime__c(Name = 'Track Time ' + taskId, Sprint__c = sprintId, Task__c = taskId, Subtask__c = subtaskId, Track__c = trackTime);
        selector.save(track);
    }

    public List<TrackTime__c> getTrackTimes(String subtaskId) {


        AbstractSelector selector = (AbstractSelector) Application.Selector.get(TrackTime__c.getSObjectType());

        return (List<TrackTime__c>) selector.queryBuilder()
                .querySelect()
                .queryFields('Id, Name, Track__c, CreatedDate, Task__c, Sprint__c, Subtask__c')
                .queryFrom(TrackTime__c.getSObjectType())
                .queryWhere('Subtask__c', subtaskId)
                .execute();
    }

}