src/objects/Sprint__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subtask__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Subtasks</relationshipLabel>
        <relationshipName>Subtasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Subtasks</relationshipLabel>
        <relationshipName>Subtasks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtask</label>
    <nameField>
        <label>Subtask Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subtasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Application.cls
/**
 * Created by YuriiDyvak on 23.07.2019.
 */

public class Application {

    public static final Factory.ServiceFactory Service = new Factory.ServiceFactory(
            new Map<Type, Type>{
                    RecordListComponentService.class => RecordListComponentService.class,
                    FieldSetService.class => FieldSetService.class,
                    ScrumProjectService.class => ScrumProjectService.class,
                    ScrumSprintService.class => ScrumSprintService.class,
                    ScrumBacklogService.class => ScrumBacklogService.class,
                    ScrumSubtaskService.class => ScrumSubtaskService.class,
                    ScrumTrackTimeService.class => ScrumTrackTimeService.class,
                    ScrumTaskService.class => ScrumTaskService.class,
                    OrgIntegrationService.class => OrgIntegrationService.class
            });

    public static final Factory.UtilFactory Util = new Factory.UtilFactory(
            new Map<Type, Type>{
                    SchemaUtil.class => SchemaUtil.class
            });

    public static final Factory.SelectorFactory Selector = new Factory.SelectorFactory(
            new Map<SObjectType, Type>{
                    Account.getSObjectType() => UniversalSelector.class,
                    Contact.getSObjectType() => UniversalSelector.class,
                    Sprint__c.getSObjectType() => UniversalSelector.class,
                    Project__c.getSObjectType() => UniversalSelector.class,
                    Task__c.getSObjectType() => UniversalSelector.class,
                    TrackTime__c.getSObjectType() => UniversalSelector.class,
                    Subtask__c.getSObjectType() => UniversalSelector.class
            });

}