src/objects/Subtask__c.object
<CustomObject>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Subtasks</relationshipLabel>
        <relationshipName>Subtasks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtask</label>
    <nameField>
        <label>Subtask Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subtasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Total_Spend_Time__c</fullName>
        <label>Total Spend Time</label>
        <summarizedField>Subtask__c.SpendTime__c</summarizedField>
        <summaryForeignKey>Subtask__c.Task__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScrumTaskService.cls
/**
 * Created by YuriiDyvak on 15.08.2019.
 */

public with sharing class ScrumTaskService {

    public void updateTaskSpendTime(List<TrackTime__c> newTrackTimes) {
        List<Task__c> result = new List<Task__c>();

        Set<Id> taskIds = new Set<Id>();
        for (TrackTime__c trackTime : newTrackTimes) {
            TrackTime__c track = (TrackTime__c) trackTime;
            taskIds.add(track.Task__c);
        }

        List<Task__c> tasks = [SELECT Id FROM Task__c WHERE Id = :taskIds];

        List<TrackTime__c> trackTimes = [SELECT Id, Task__c FROM TrackTime__c WHERE Subtask__c = :taskIds];

        for (Task__c task : tasks) {
            Decimal spendTime = 0;

            for (TrackTime__c trackTime : trackTimes) {
                if (trackTime.Task__c == task.Id) {
                    spendTime += trackTime.Track__c;

                }
            }

            System.debug(spendTime);
            //Task__c newTask = new Task__c(Id = task.Id, Total_Spend_Time__c = spendTime);
            //result.add(newTask);
        }

        insert result;
    }

}