src/objects/Subtask__c.object
<CustomObject>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Subtasks</relationshipLabel>
        <relationshipName>Subtasks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subtask</label>
    <nameField>
        <label>Subtask Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subtasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScrumTaskRecord.cls
/**
 * Created by YuriiDyvak on 08.08.2019.
 */

public class ScrumTaskRecord {

    @AuraEnabled
    public Double progress;

    @AuraEnabled
    public Task__c task;

    @AuraEnabled
    public List<Subtask__c> subtasks;

    public ScrumTaskRecord(Double progress, Task__c task) {
        this.progress = progress;
        this.task = task;
    }

    public ScrumTaskRecord(Task__c task) {
        this.progress = 0.00;
        this.task = task;
        this.subtasks = new List<Subtask__c>();
    }

    public ScrumTaskRecord(Task__c task, List<Subtask__c> subtasks) {
        this.progress = 0.00;
        this.task = task;
        this.subtasks = subtasks;
    }
}