src/objects/Subtask__c.object
<CustomObject>
    <fields>
        <fullName>PlanTime__c</fullName>
        <label>PlanTime</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SpendTime__c</fullName>
        <label>SpendTime</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Subtasks</relationshipLabel>
        <relationshipName>Subtasks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>new</fullName>
                </value>
                <value>
                    <fullName>in progress</fullName>
                </value>
                <value>
                    <fullName>completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subtask</label>
    <nameField>
        <label>Subtask Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subtasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>new</fullName>
                </value>
                <value>
                    <fullName>in progress</fullName>
                </value>
                <value>
                    <fullName>completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScrumSubtaskService.cls
/**
 * Created by YuriiDyvak on 07.08.2019.
 */

public class ScrumSubtaskService {

    public List<Subtask__c> getSubtasks(String taskId) {
        UniversalSelector selector = (UniversalSelector) Application.Selector.get(Subtask__c.getSObjectType());
        return (List<Subtask__c>) selector.queryBuilder()
                .querySelect()
                .queryFields('Id, Name, PlanTime__c, SpendTime__c, Type__c')
                .queryFrom(Subtask__c.getSObjectType())
                .queryWhere('Task__c', taskId)
                .execute();
    }

    public Subtask__c getSubtask(String subTaskId) {
        UniversalSelector selector = (UniversalSelector) Application.Selector.get(Subtask__c.getSObjectType());
        return (Subtask__c) selector.queryBuilder()
                .querySelect()
                .queryFields('Id, Name, PlanTime__c, SpendTime__c, Type__c')
                .queryFrom(Subtask__c.getSObjectType())
                .queryWhere('Id', subTaskId)
                .queryLimit(1)
                .execute();
    }

    public void updateSubtaskSpendTime(List<TrackTime__c> newTrackTimes) {
        List<Subtask__c> result = new List<Subtask__c>();

        Set<Id> subtaskIds = new Set<Id>();
        for (SObject trackTime : newTrackTimes) {
            TrackTime__c track = (TrackTime__c) trackTime;
            subtaskIds.add(track.Subtask__c);
        }

        List<Subtask__c> subtasks = [SELECT Id FROM Subtask__c WHERE Id = :subtaskIds];

        List<TrackTime__c> trackTimes = [SELECT Id, Subtask__c, Track__c FROM TrackTime__c WHERE Subtask__c = :subtaskIds];

        for (Subtask__c subtask : subtasks) {
            Decimal spendTime = 0;

            for (TrackTime__c trackTime : trackTimes) {
                if (trackTime.Subtask__c == subtask.Id) {
                    spendTime += trackTime.Track__c;
                }
            }

            subtask.SpendTime__c = spendTime;
            result.add(subtask);
        }

        update result;
    }

    public void updateSubtaskSpendTime(String subtaskId) {
        List<Subtask__c> result = new List<Subtask__c>();

        Set<Id> subtaskIds = new Set<Id>();
        subtaskIds.add(Id.valueOf(subtaskId));

        List<Subtask__c> subtasks = [SELECT Id FROM Subtask__c WHERE Id = :subtaskIds];

        List<TrackTime__c> trackTimes = [SELECT Id, Subtask__c, Track__c FROM TrackTime__c WHERE Subtask__c = :subtaskIds];

        for (Subtask__c subtask : subtasks) {
            Decimal spendTime = 0;

            for (TrackTime__c trackTime : trackTimes) {
                if (trackTime.Subtask__c == subtask.Id) {
                    spendTime += trackTime.Track__c;
                }
            }

            subtask.SpendTime__c = spendTime;
            result.add(subtask);
        }

        update result;
    }

    public void removeTrackTime(String trackId) {
        UniversalSelector selector = (UniversalSelector) Application.Selector.get(TrackTime__c.getSObjectType());
        selector.deleteById(trackId);
    }

}